[book]
authors = ["ktarrant"]
language = "en"
src = "src"
title = "Pokemon Walkthrough"

[output.html]
additional-css = ["theme/pokemon.css"]

[preprocessor.autosummary]
command = "mdbook-autosummary"

[build]
create-missing = false
